apiVersion: v1
kind: ConfigMap
metadata:
  name: lone1-config
  namespace: lone1

data:
  MONGO_URI: "mongodb://mongodb:27017/lone1"
  MONGO_DB_NAME: "lone1"

  ML_PREDICTOR_URL: "http://ml-predictor-service:8001"
  ML_TRAINER_URL: "http://ml-trainer-service:8002"

  SERVICE_NAME: "loan-default-system"
